name: newline-action
description: Find missing new lines on files
author: Lee Packham

branding:
  icon: file
  color: white

inputs:
  config-path:
    description: The optional configuration file path.
    default: .github/newline.yml

runs:
  using: 'node12'
  main: 'dist/index.js'
